### ISSUE TITLE
Přesunout na Netlify

### ISSUE THREAD

**Issue by vasimi** [MozillaCZ/prezentace#3]
@MikkCZ Vím, že jsme nemohli dát prezentace na subdoménu, protože tam nešlo dát HTTPS. Když teď weby přesouváme na Netlify, co přesunout i tohle a hodit to na prezentace.mozilla.cz?

**Comment by MikkCZ** [comment]
Funguje přesměrování z https://www.mozilla.cz/prezentace/. Nejsem si jistý, jestli přesun tohodle seznamu na Netlify a zavedení další subdomény něčemu prospěje.

**Comment by vasimi** [comment]
Minimálně to vypadá líp, než mozillacz.github.io/prezentace. A přijde mi to i praktičtější.
